version: '3'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db_wordpress
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      VIRTUAL_HOST: wordpress1.valle.ml
      VIRTUAL_PORT: 80
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 

  db_wordpress:
    image: mysql:latest
    container_name: db_wordpress
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-wordp
      environment:
        PMA_HOST: db_wordpress
        VIRTUAL_HOST: pma1.valle.ml
        VIRTUAL_PORT: 80
      restart: always
      expose:
       - 80
      volumes:
       - /sessions

volumes:
  wordpress:
  db:

networks:
  default:
    external:
      name: nginx-proxy
