version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    ports:
     - "3308:3306"
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - MAGENTO_HOST=magento.valle.ml
      - VIRTUAL_HOST=magento.valle.ml
      - VIRTUAL_PORT=80
    expose:
      - 80
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-mag
      environment:
        PMA_HOST: web3_mariadb_1
        VIRTUAL_HOST: pma3.valle.ml
        VIRTUAL_PORT: 80
        restart: always
      expose:
       - 80
      volumes:
       - /sessions

volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy

